In [3]:
import gym
import numpy as np
import random
import time
from IPython.display import clear_output

In [5]:
env=gym.make("FrozenLake-v1")

In [11]:
action_space_size=env.action_space.n
state_space_size=env.observation_space.n

q_table=np.zeros((state_space_size,action_space_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [87]:
num_episodes=15000
max_steps_per_episode=100

learning_rate=0.1
discount_rate=0.99

exploration_rate=1
max_exploration_rate=1
min_exploration_rate=0.01
exploration_decay_rate=0.005

In [88]:
rewards_all_episodes=[]

#Q-learning algorithm
for episode in range(num_episodes):
    state=env.reset()
    done=False
    rewards_current_episode=0
    
    for step in range(max_steps_per_episode):
        exploration_rate_threshold=random.uniform(0,1)
        if exploration_rate_threshold>exploration_rate:
            action=np.argmax(q_table[state,:])
        else:
            action=env.action_space.sample()
            
        new_state, reward, done, info = env.step(action)
        
        # Update Q-table for Q(s,a)
        q_table[state,action]=q_table[state,action] * (1-learning_rate)+ \
            learning_rate*(reward+discount_rate*np.max(q_table[new_state,:]))
        
        state=new_state
        rewards_current_episode+= reward
        
        if done== True:
            break
     # Exploration rate decay
    exploration_rate=min_exploration_rate+ \
    (max_exploration_rate-min_exploration_rate)* \
    np.exp(-exploration_decay_rate*episode)
    
    rewards_all_episodes.append(rewards_current_episode)

#Calculate and print the average rewards per thousand episodes
rewards_per_thousand_episodes =np.split(np.array(rewards_all_episodes),num_episodes/1000)
count=1000
print("****************Average rewards per thousand episodes*************\n")

for r in rewards_per_thousand_episodes:
    print(count, ": ",str(sum(r/1000)))
    count+=1000
    
#print updated Q_table
print("\n\n*********************Q-table***************")
print(q_table)
    

****************Average rewards per thousand episodes*************

1000 :  0.36200000000000027
2000 :  0.6920000000000005
3000 :  0.6850000000000005
4000 :  0.6690000000000005
5000 :  0.6980000000000005
6000 :  0.6970000000000005
7000 :  0.6480000000000005
8000 :  0.6920000000000005
9000 :  0.6980000000000005
10000 :  0.7140000000000005
11000 :  0.6680000000000005
12000 :  0.6860000000000005
13000 :  0.7080000000000005
14000 :  0.7010000000000005
15000 :  0.7170000000000005


*********************Q-table***************
[[0.59809976 0.52255748 0.51222413 0.50452939]
 [0.39284233 0.32847743 0.35720982 0.52722402]
 [0.43093844 0.42203301 0.38461649 0.47059275]
 [0.30451356 0.32832759 0.33506687 0.4441204 ]
 [0.61089717 0.38602583 0.51736283 0.42294829]
 [0.         0.         0.         0.        ]
 [0.36834506 0.08669318 0.2259025  0.1606676 ]
 [0.         0.         0.         0.        ]
 [0.35370616 0.40180104 0.39627047 0.64521709]
 [0.52034062 0.69192903 0.42302066 0.46760757]
 [0.

In [93]:
for episode in range(3):
    state=env.reset()
    done=False
    print("******EPISODE", episode+1, "**********\n\n\n\n")
    time.sleep(1)
    
    for step in range(max_steps_per_episode):
        clear_output(wait=True)
        env.render()
        time.sleep(0.3)
        
        action= np.argmax(q_table[state,:])
        new_state, reward, done, info = env.step(action)
        
        if done:
            clear_output(wait=True)
            env.render()
            if reward == 1:
                print("******you reached the goal!******")
                time.sleep(3)
            else:
                print("******you fell through a hole!*****")
                time.sleep(3)
            clear_output(wait=True)
            break
            
        state=new_state
        
env.close()

  (Down)
SFFF
FHFH
FFFH
HFFG
******you reached the goal!******
